global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'spring-boot-services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'user-service:8081'
          - 'energy-service:8082'
          - 'device-service:8083'
          - 'analytics-service:8084'
          - 'billing-service:8085'
          - 'api-gateway:8080' 